// Starter exemplars, part 3: colour with a legend in comparisons and quality
// maps, a star as the goal, radial idea boards mixing tasks, links, frames and
// a zone, an uncertain cause, and a site plan with a portal and a fork.
import type { AuthoredExemplar } from "../types";
import { node, props, rel } from "./helpers";

export const STARTER_3: AuthoredExemplar[] = [
  {
    id: "popup-vs-lease",
    title: "Pop-up vs. permanent studio",
    note: "A two-way comparison coloured by meaning, risks against opportunities, with a legend; the topics stay uncoloured because they are neither.",
    labels: ["space", "decision"],
    input: {
      type: "comparison",
      title: "Pop-up or permanent studio",
      text: "Should we run a six-month pop-up in the market hall or sign a five-year lease on a permanent studio? List what each offers and what could go wrong.",
      cards: [],
    },
    graph: {
      mapType: "doubleBubble",
      title: "Pop-up vs. permanent studio",
      legend: [{ tint: "rose", meaning: "Risk" }, { tint: "emerald", meaning: "Opportunity" }],
      nodes: [
        node("lt", "leftTopic", "Six-month pop-up", { kind: "bubble" }),
        node("rt", "rightTopic", "Five-year lease", { kind: "bubble" }),
        node("s1", "shared", "Builds a local audience", { kind: "bubble", tint: "emerald" }),
        node("s2", "shared", "Needs a fit-out budget", { kind: "bubble", tint: "rose" }),
        node("l1", "leftOnly", "Test demand cheaply", { kind: "bubble", tint: "emerald" }),
        node("l2", "leftOnly", "Market foot traffic", { kind: "bubble", tint: "emerald" }),
        node("l3", "leftOnly", "Must move out in autumn", { kind: "bubble", tint: "rose" }),
        node("r1", "rightOnly", "Room for a sound lab", { kind: "bubble", tint: "emerald" }),
        node("r2", "rightOnly", "Locked into rent", { kind: "bubble", tint: "rose" }),
      ],
      relations: [],
    },
  },
  {
    id: "ocean-room-qualities",
    title: "What makes the ocean room unforgettable",
    note: "Qualities are bubbles, the goal they serve is a strong star, and colour separates what visitors sense from what they feel.",
    labels: ["museum", "qualities"],
    input: {
      type: "topic",
      title: "An unforgettable ocean room",
      text: "What qualities make the ocean room unforgettable? Separate what visitors sense from what they feel.",
      cards: [],
    },
    graph: {
      mapType: "bubble",
      title: "What makes the ocean room unforgettable",
      legend: [{ tint: "violet", meaning: "Sensed" }, { tint: "ocean", meaning: "Felt" }],
      nodes: [
        node("c", "center", "Unforgettable ocean room", { kind: "shape", emphasis: "strong", props: props({ shapeType: "star" }) }),
        node("q1", "quality", "Slowed whale song", { kind: "bubble", tint: "violet" }),
        node("q2", "quality", "Caustic light", { kind: "bubble", tint: "violet" }),
        node("q3", "quality", "Cool mist", { kind: "bubble", tint: "violet" }),
        node("q4", "quality", "Calm that deepens", { kind: "bubble", tint: "ocean" }),
        node("q5", "quality", "Awe at scale", { kind: "bubble", tint: "ocean" }),
        node("q6", "quality", "Safe to lie still", { kind: "bubble", tint: "ocean" }),
      ],
      relations: [],
    },
  },
  {
    id: "remote-crew-ideas",
    title: "Keeping the remote crew engaged",
    note: "Brainstormed ideas around one question, coloured quick win or bigger bet as asked, with the one owned action as a task and the article as a link.",
    labels: ["community", "ideas"],
    input: {
      type: "brainDump",
      title: "Keeping the remote crew engaged",
      text: "between our in-person weekends people drift. ideas: monthly online listening party, a shared playlist, pairing new people with old hands (Nadia offered to run that), a small print zine twice a year (bigger job), a members' map of where everyone is, and the handbook page about async rituals that Nadia sent. quick wins first please, but mark the bigger bets.",
      cards: [],
    },
    graph: {
      mapType: "radial",
      title: "Keeping the remote crew engaged",
      legend: [{ tint: "sunset", meaning: "Quick win" }, { tint: "ocean", meaning: "Bigger bet" }],
      nodes: [
        node("c", "center", "Between weekends", { detail: "Keep people connected", props: props({ emoji: "🌍" }) }),
        node("b1", "branch", "Monthly listening party", { tint: "sunset", props: props({ emoji: "🎧" }) }),
        node("b2", "branch", "Shared playlist", { tint: "sunset" }),
        node("b3", "branch", "Pair newcomers with old hands", { kind: "task", tint: "sunset", props: props({ owner: "Nadia" }) }),
        node("b4", "branch", "Print zine, twice a year", { tint: "ocean" }),
        node("b5", "branch", "Members' map", { tint: "ocean", detail: "Where everyone lives and works" }),
        node("b6", "branch", "Async rituals handbook", { kind: "link", props: props({ url: "https://handbook.gitlab.com/handbook/company/culture/all-remote/" }) }),
      ],
      relations: [],
    },
  },
  {
    id: "studio-launch",
    title: "Studio launch",
    note: "Launch cards around a hexagon building block: the press kit is a zone to fill, the opening night a frame, the booking page a link and the flyer drop a task.",
    labels: ["launch"],
    input: {
      type: "canvasCards",
      title: "Studio launch board",
      text: "Arrange these launch cards around the opening week.",
      cards: [
        { title: "Press kit", body: "Photos, founder story, price list" },
        { title: "Opening night", body: "Candlelit sound bath for 40" },
        { title: "Launch post", body: "Instagram carousel" },
        { title: "Neighbour flyers", body: "Leo drops 500 in the street" },
        { title: "Booking page", body: "Live a week before" },
      ],
    },
    graph: {
      mapType: "radial",
      title: "Studio launch",
      legend: [],
      nodes: [
        node("c", "center", "Opening week", { kind: "shape", props: props({ shapeType: "hexagon" }) }),
        node("b1", "branch", "Press kit", { kind: "zone", detail: "Photos, founder story, price list" }),
        node("b2", "branch", "Opening night", { kind: "frame", props: props({ storyboard: true, description: "Candlelit sound bath for 40" }) }),
        node("b3", "branch", "Launch post", { detail: "Instagram carousel", props: props({ emoji: "📣" }) }),
        node("b4", "branch", "Drop 500 neighbour flyers", { kind: "task", props: props({ owner: "Leo" }) }),
        node("b5", "branch", "Booking page", { kind: "link", detail: "Live a week before", props: props({ url: "https://example.com/book" }) }),
      ],
      relations: [],
    },
  },
  {
    id: "tea-ceremony-senses",
    title: "Morning tea ceremony, by sense",
    note: "Sensory cards become qualities around the ritual, coloured by the sense they reach, with a legend so the palette reads at a glance.",
    labels: ["ritual", "senses"],
    input: {
      type: "canvasCards",
      title: "Tea ceremony cards",
      text: "Sort these cards for the morning tea ceremony by the sense each one reaches.",
      cards: [
        { title: "Steam rising", body: "From the kettle" },
        { title: "Bamboo whisk", body: "Soft rhythmic sound" },
        { title: "Matcha bitterness", body: "The first sip" },
        { title: "Cool stone floor", body: "Bare feet" },
        { title: "Paper lantern light", body: "Soft and low" },
        { title: "Birdsong recording", body: "Fades in at the end" },
      ],
    },
    graph: {
      mapType: "bubble",
      title: "Morning tea ceremony, by sense",
      legend: [{ tint: "glacier", meaning: "Sound" }, { tint: "sunset", meaning: "Touch and taste" }, { tint: "rose", meaning: "Sight" }],
      nodes: [
        node("c", "center", "Morning tea ceremony", { props: props({ emoji: "🍵" }) }),
        node("q1", "quality", "Bamboo whisk rhythm", { kind: "bubble", tint: "glacier" }),
        node("q2", "quality", "Birdsong fade-out", { kind: "bubble", tint: "glacier" }),
        node("q3", "quality", "Bitter first sip", { kind: "bubble", tint: "sunset" }),
        node("q4", "quality", "Cool stone underfoot", { kind: "bubble", tint: "sunset" }),
        node("q5", "quality", "Steam rising", { kind: "bubble", tint: "rose" }),
        node("q6", "quality", "Lantern glow", { kind: "bubble", tint: "rose" }),
      ],
      relations: [],
    },
  },
  {
    id: "venue-cancellation",
    title: "If the venue cancels",
    note: "A rumour is a caption with a dashed link because it is uncertain; the effects we must act on are tasks with owners.",
    labels: ["risk", "event"],
    input: {
      type: "comparison",
      title: "Venue cancellation: causes and knock-ons",
      text: "What could cause our venue to cancel the autumn gathering, and what would that lead to? Include what we'd need to do if it happens. Ivy handles guests, Sam handles venues.",
      cards: [],
    },
    graph: {
      mapType: "multiFlow",
      title: "If the venue cancels",
      legend: [],
      nodes: [
        node("k1", "cause", "Single venue option", { detail: "Nothing else in town fits 120" }),
        node("k2", "cause", "Late deposit", { detail: "Paid two weeks after the deadline" }),
        node("k3", "cause", "Owner may sell the building (rumour)", { kind: "caption" }),
        node("ev", "event", "Venue cancels", { emphasis: "strong", props: props({ emoji: "⚠️" }) }),
        node("e1", "effect", "Refund requests"),
        node("e2", "effect", "Call every ticket holder", { kind: "task", props: props({ owner: "Ivy" }) }),
        node("e3", "effect", "Shortlist two backup venues", { kind: "task", props: props({ owner: "Sam" }) }),
      ],
      relations: [
        rel("k1", "ev"),
        rel("k2", "ev"),
        rel("k3", "ev", "", { style: "dashed" }),
        rel("ev", "e1"),
        rel("ev", "e2"),
        rel("ev", "e3"),
      ],
    },
  },
  {
    id: "festival-site",
    title: "Listening festival site",
    note: "A site plan where the stages are a portal (too big for this map), food is a zone to sketch in, safety sits under a heading and the late-night question is a fork.",
    labels: ["festival", "site plan"],
    input: {
      type: "topic",
      title: "Festival site plan",
      text: "Plan the site for a two-day listening festival: stages, food, safety and the late-night decision about the silent disco.",
      cards: [],
    },
    graph: {
      mapType: "spider",
      title: "Listening festival site",
      legend: [],
      nodes: [
        node("c", "center", "Festival site", { props: props({ emoji: "🎪" }) }),
        node("b1", "branch", "Stages", { kind: "portal", parent: "c", detail: "Main, forest and dome stages", props: props({ icon: "grid" }) }),
        node("b2", "branch", "Food court", { kind: "zone", parent: "c", detail: "Sketch the vendor layout here" }),
        node("b3", "branch", "Safety", { kind: "heading", parent: "c" }),
        node("b4", "branch", "Silent disco after 11?", { kind: "waypoint", parent: "c", emphasis: "strong", props: props({ shapeType: "diamond" }) }),
        node("f1", "leaf", "Twelve vendors", { parent: "b2", detail: "Vegan and gluten-free options" }),
        node("f2", "leaf", "Water refill points", { parent: "b2" }),
        node("s1", "leaf", "Medical tent", { parent: "b3" }),
        node("s2", "leaf", "Gate security", { parent: "b3" }),
        node("s3", "leaf", "Fire marshal walkthrough", { kind: "task", parent: "b3", props: props({ owner: "Site lead" }) }),
        node("d1", "leaf", "Yes: headphones at the dome", { parent: "b4" }),
        node("d2", "leaf", "No: close at 11", { parent: "b4" }),
      ],
      relations: [rel("b4", "d1", "if permit"), rel("b4", "d2", "if not")],
    },
  },
];
