// Starter exemplars, part 2: a strong main path to a star goal with a dotted
// loop, owners' actions as tasks under headings, two framing anchors, and
// concept maps with uncertain, mutual and sourced relations.
import type { AuthoredExemplar } from "../types";
import { node, props, rel } from "./helpers";

export const STARTER_2: AuthoredExemplar[] = [
  {
    id: "onboarding-path",
    title: "The path to a first calm session",
    note: "Shuffled onboarding cards put in order: plain steps as rectangles, the choice as a waypoint, the goal as a strong star, the main path strong and the retry loop dotted.",
    labels: ["onboarding", "app"],
    input: {
      type: "canvasCards",
      title: "Onboarding cards, shuffled",
      text: "Put these onboarding moments in order and show the path we want every new member to take.",
      cards: [
        { title: "Choose an intention", body: "Sleep, focus or calm" },
        { title: "Welcome screen", body: "The brand promise" },
        { title: "Set a reminder", body: "Pick a time of day" },
        { title: "First calm session", body: "Five minutes, guided" },
        { title: "Create account", body: "Email or Apple" },
      ],
    },
    graph: {
      mapType: "flow",
      title: "The path to a first calm session",
      legend: [],
      nodes: [
        node("w1", "step", "Welcome screen", { kind: "shape", props: props({ shapeType: "rectangle" }) }),
        node("w2", "step", "Create account", { kind: "shape", props: props({ shapeType: "rectangle" }) }),
        node("w3", "step", "Choose an intention", { kind: "waypoint", props: props({ shapeType: "diamond" }) }),
        node("w4", "step", "Set a reminder", { detail: "Pick a time of day", props: props({ emoji: "⏰" }) }),
        node("w5", "step", "First calm session", { kind: "shape", emphasis: "strong", props: props({ shapeType: "star" }) }),
      ],
      relations: [
        rel("w1", "w2", "", { weight: "strong" }),
        rel("w2", "w3", "", { weight: "strong" }),
        rel("w3", "w4", "", { weight: "strong" }),
        rel("w4", "w5", "", { weight: "strong" }),
        rel("w5", "w3", "try another intention", { style: "dotted" }),
      ],
    },
  },
  {
    id: "sprint-day-owners",
    title: "Design sprint day",
    note: "A day broken into parts under headings; everything someone owns is a task with that owner, and group activities stay cards.",
    labels: ["workshop", "agenda"],
    input: {
      type: "brainDump",
      title: "Design sprint day, who does what",
      text: "sprint day next thursday. morning: Ana opens with the challenge (15 min), then expert interviews, Leo runs those, then how-might-we notes, everyone. afternoon: Mia runs the dot vote, then sketching in silence, then Sam picks two concepts with the client. I need to book the room and print the templates.",
      cards: [],
    },
    graph: {
      mapType: "brace",
      title: "Design sprint day",
      legend: [],
      nodes: [
        node("w", "whole", "Sprint day", { detail: "Thursday, 9:30 to 17:00", props: props({ emoji: "🏃" }) }),
        node("a", "part", "Morning", { kind: "heading", parent: "w" }),
        node("b", "part", "Afternoon", { kind: "heading", parent: "w" }),
        node("p", "part", "Prep", { kind: "heading", parent: "w" }),
        node("a1", "subpart", "Open with the challenge", { kind: "task", parent: "a", detail: "15 minutes", props: props({ owner: "Ana" }) }),
        node("a2", "subpart", "Run expert interviews", { kind: "task", parent: "a", props: props({ owner: "Leo" }) }),
        node("a3", "subpart", "How-might-we notes", { parent: "a", detail: "Everyone writes, one idea per note" }),
        node("b1", "subpart", "Run the dot vote", { kind: "task", parent: "b", props: props({ owner: "Mia" }) }),
        node("b2", "subpart", "Silent sketching", { parent: "b", detail: "Crazy 8s, then solution sketches" }),
        node("b3", "subpart", "Pick two concepts with the client", { kind: "task", parent: "b", props: props({ owner: "Sam" }) }),
        node("p1", "subpart", "Book the room", { kind: "task", parent: "p", props: props({ owner: "Me" }) }),
        node("p2", "subpart", "Print the templates", { kind: "task", parent: "p", props: props({ owner: "Me" }) }),
      ],
      relations: [],
    },
  },
  {
    id: "retreat-purpose",
    title: "What the retreat is for",
    note: "Purpose content anchors onto two different framing sections (intention and desired change), so the map feeds the framing instead of duplicating it.",
    labels: ["retreat", "framing"],
    input: {
      type: "topic",
      title: "What the retreat is for",
      text: "Break down what our breathwork retreat is for: the intention behind it and the change we hope guests leave with.",
      cards: [],
    },
    graph: {
      mapType: "brace",
      title: "What the retreat is for",
      legend: [],
      nodes: [
        node("w", "whole", "Breathwork retreat", { detail: "Three days, 12 guests", props: props({ emoji: "🌬️" }) }),
        node("i", "part", "Intention", { kind: "anchor", parent: "w", props: props({ componentKey: "intentionCore" }) }),
        node("d", "part", "Desired change", { kind: "anchor", parent: "w", props: props({ componentKey: "desiredChange" }) }),
        node("i1", "subpart", "Slow down on purpose", { parent: "i" }),
        node("i2", "subpart", "Breath as an anchor", { parent: "i" }),
        node("i3", "subpart", "Guests choose their own pace", { kind: "caption", parent: "i" }),
        node("d1", "subpart", "Sleep better within a week", { parent: "d" }),
        node("d2", "subpart", "A daily 5-minute practice", { parent: "d" }),
      ],
      relations: [],
    },
  },
  {
    id: "wellness-ecosystem",
    title: "Neighbourhood wellness ecosystem",
    note: "Unproven links are dashed, mutual ones two-way, a loose association has no arrow, and the studio's main relationship is strong.",
    labels: ["ecosystem", "partners"],
    input: {
      type: "topic",
      title: "Neighbourhood wellness ecosystem",
      text: "How do our studio, local therapists, the council's green spaces, a wellbeing app partner and our members relate to each other? Some of these relationships are still unproven.",
      cards: [],
    },
    graph: {
      mapType: "conceptMap",
      title: "Neighbourhood wellness ecosystem",
      legend: [],
      nodes: [
        node("st", "concept", "Our studio", { emphasis: "strong", props: props({ emoji: "🏛️" }) }),
        node("me", "concept", "Members"),
        node("th", "concept", "Local therapists"),
        node("gs", "concept", "Council green spaces"),
        node("ap", "concept", "Wellbeing app partner"),
        node("tr", "concept", "Trust", { kind: "bubble" }),
      ],
      relations: [
        rel("st", "me", "serves", { weight: "strong" }),
        rel("th", "st", "refer clients", { direction: "both" }),
        rel("gs", "st", "hosts sessions", { style: "dashed" }),
        rel("ap", "me", "nudges", { style: "dashed" }),
        rel("me", "tr", "builds"),
        rel("tr", "th", "linked to", { style: "dotted", direction: "none" }),
      ],
    },
  },
  {
    id: "community-evidence",
    title: "What backs our community bet",
    note: "Sources become links attached to the finding each one supports, and the open question stays a caption so it is not mistaken for a finding.",
    labels: ["research", "community"],
    input: {
      type: "canvasCards",
      title: "Research brief cards",
      text: "Connect these findings and sources so the team sees what backs what.",
      cards: [
        { title: "Loneliness drives sign-ups", body: "Top reason in 40 interviews" },
        { title: "Rituals build belonging", body: "Weekly tea circle regulars" },
        { title: "Small groups retain members", body: "Under 12 feels intimate" },
        { title: "Source: ONS wellbeing data", body: "ons.gov.uk" },
        { title: "Source: APA on social support", body: "apa.org" },
        { title: "Does this hold online?", body: "Nobody has checked" },
      ],
    },
    graph: {
      mapType: "conceptMap",
      title: "What backs our community bet",
      legend: [],
      nodes: [
        node("f1", "concept", "Loneliness drives sign-ups", { detail: "Top reason in 40 interviews" }),
        node("f2", "concept", "Rituals build belonging", { detail: "Weekly tea circle regulars" }),
        node("f3", "concept", "Small groups retain members", { detail: "Under 12 feels intimate" }),
        node("l1", "concept", "ONS wellbeing data", { kind: "link", props: props({ url: "https://www.ons.gov.uk/peoplepopulationandcommunity/wellbeing" }) }),
        node("l2", "concept", "APA on social support", { kind: "link", props: props({ url: "https://www.apa.org/topics/social-support" }) }),
        node("q", "concept", "Open question: does this hold online?", { kind: "caption" }),
      ],
      relations: [
        rel("f1", "f2", "leads people to"),
        rel("f2", "f3", "strongest in"),
        rel("l1", "f1", "supports"),
        rel("l2", "f3", "supports"),
        rel("q", "f3", "questions", { style: "dotted" }),
      ],
    },
  },
];
