// Starter exemplars, part 2: a strong main path to a star goal with a dotted
// loop, owners' actions as tasks under headings, two framing anchors, and
// concept maps with uncertain, mutual and sourced relations. Every fact in a
// graph is in its input (faithful.ts).
import type { AuthoredExemplar } from "../types";
import { node, props, rel } from "./helpers";

export const STARTER_2: AuthoredExemplar[] = [
  {
    id: "onboarding-path",
    title: "The path to a first calm session",
    note: "Because the cards are steps in one order, they are a flow of plain rectangles; the choice is a waypoint, the goal a strong star, and the retry card the dotted loop back.",
    labels: ["onboarding", "app"],
    input: {
      type: "canvasCards",
      title: "Onboarding cards, shuffled",
      text: "Put these onboarding moments in order and show the path we want every new member to take.",
      cards: [
        { title: "Choose an intention", body: "Sleep, focus or calm" },
        { title: "Welcome screen", body: "The brand promise" },
        { title: "Set a reminder", body: "Pick a time of day" },
        { title: "First calm session", body: "Five minutes, guided" },
        { title: "Create account", body: "Email or Apple" },
        { title: "If the session doesn't land", body: "Try another intention" },
      ],
    },
    graph: {
      mapType: "flow",
      title: "The path to a first calm session",
      legend: [],
      nodes: [
        node("w1", "step", "Welcome screen", { kind: "shape", detail: "The brand promise", props: props({ shapeType: "rectangle" }) }),
        node("w2", "step", "Create account", { kind: "shape", detail: "Email or Apple", props: props({ shapeType: "rectangle" }) }),
        node("w3", "step", "Choose an intention", { kind: "waypoint", detail: "Sleep, focus or calm", props: props({ shapeType: "diamond" }) }),
        node("w4", "step", "Set a reminder", { kind: "shape", detail: "Pick a time of day", props: props({ shapeType: "rectangle" }) }),
        node("w5", "step", "First calm session", { kind: "shape", emphasis: "strong", detail: "Five minutes, guided", props: props({ shapeType: "star" }) }),
      ],
      relations: [
        rel("w1", "w2", "", { weight: "strong" }),
        rel("w2", "w3", "", { weight: "strong" }),
        rel("w3", "w4", "", { weight: "strong" }),
        rel("w4", "w5", "", { weight: "strong" }),
        rel("w5", "w3", "try another intention", { style: "dotted" }),
      ],
    },
  },
  {
    id: "sprint-day-owners",
    title: "Design sprint day",
    note: "Because the day splits into morning, afternoon and prep, each is a heading over its parts; what a named person owns is a task, and what everyone does stays a card.",
    labels: ["workshop", "agenda"],
    input: {
      type: "brainDump",
      title: "Design sprint day, who does what",
      text: "sprint day next thursday. morning: Aiko opens with the challenge (15 min), then expert interviews, Dev runs those, then how-might-we notes, everyone. afternoon: Marta runs the dot vote, then sketching in silence, then Kwame picks two concepts with the client. Noor books the room and prints the templates.",
      cards: [],
    },
    graph: {
      mapType: "brace",
      title: "Design sprint day",
      legend: [],
      nodes: [
        node("w", "whole", "Sprint day", { detail: "Next Thursday", props: props({ emoji: "🏃" }) }),
        node("a", "part", "Morning", { kind: "heading", parent: "w" }),
        node("b", "part", "Afternoon", { kind: "heading", parent: "w" }),
        node("p", "part", "Prep", { kind: "heading", parent: "w" }),
        node("a1", "subpart", "Open with the challenge", { kind: "task", parent: "a", detail: "15 min", props: props({ owner: "Aiko" }) }),
        node("a2", "subpart", "Run expert interviews", { kind: "task", parent: "a", props: props({ owner: "Dev" }) }),
        node("a3", "subpart", "How-might-we notes", { parent: "a", detail: "Everyone" }),
        node("b1", "subpart", "Run the dot vote", { kind: "task", parent: "b", props: props({ owner: "Marta" }) }),
        node("b2", "subpart", "Sketching in silence", { parent: "b" }),
        node("b3", "subpart", "Pick two concepts with the client", { kind: "task", parent: "b", props: props({ owner: "Kwame" }) }),
        node("p1", "subpart", "Book the room", { kind: "task", parent: "p", props: props({ owner: "Noor" }) }),
        node("p2", "subpart", "Print the templates", { kind: "task", parent: "p", props: props({ owner: "Noor" }) }),
      ],
      relations: [],
    },
  },
  {
    id: "retreat-purpose",
    title: "What the retreat is for",
    note: "Because the content is the retreat's intention and the change it hopes for, each part anchors to that framing section, so the map feeds the framing instead of repeating it.",
    labels: ["retreat", "framing"],
    input: {
      type: "topic",
      title: "What the retreat is for",
      text: "Break down what our breathwork retreat is for. The intention: slow down on purpose, use the breath as an anchor, and let guests choose their own pace. The change we hope guests leave with: better sleep and a short daily practice they keep.",
      cards: [],
    },
    graph: {
      mapType: "brace",
      title: "What the retreat is for",
      legend: [],
      nodes: [
        node("w", "whole", "Breathwork retreat", { props: props({ emoji: "🌬️" }) }),
        node("i", "part", "Intention", { kind: "anchor", parent: "w", props: props({ componentKey: "intentionCore" }) }),
        node("d", "part", "Desired change", { kind: "anchor", parent: "w", props: props({ componentKey: "desiredChange" }) }),
        node("i1", "subpart", "Slow down on purpose", { parent: "i" }),
        node("i2", "subpart", "Breath as an anchor", { parent: "i" }),
        node("i3", "subpart", "Guests choose their own pace", { parent: "i" }),
        node("d1", "subpart", "Better sleep", { parent: "d" }),
        node("d2", "subpart", "A short daily practice they keep", { parent: "d" }),
      ],
      relations: [],
    },
  },
  {
    id: "wellness-ecosystem",
    title: "Neighbourhood wellness ecosystem",
    note: "Because the content is how players relate, relations carry the meaning: unproven ones dashed, the mutual one two-way, a loose overlap with no arrow, the studio's main tie strong.",
    labels: ["ecosystem", "partners"],
    input: {
      type: "topic",
      title: "Neighbourhood wellness ecosystem",
      text: "How do our studio, local therapists, the council's green spaces, a wellbeing app partner and our members relate to each other, and where does trust come in? The green spaces and the app partner are still unproven.",
      cards: [],
    },
    graph: {
      mapType: "conceptMap",
      title: "Neighbourhood wellness ecosystem",
      legend: [],
      nodes: [
        node("st", "concept", "Our studio", { emphasis: "strong", props: props({ emoji: "🏛️" }) }),
        node("me", "concept", "Members"),
        node("th", "concept", "Local therapists"),
        node("gs", "concept", "Council green spaces"),
        node("ap", "concept", "Wellbeing app partner"),
        node("tr", "concept", "Trust", { kind: "bubble" }),
      ],
      relations: [
        rel("st", "me", "serves", { weight: "strong" }),
        rel("th", "st", "refer clients", { direction: "both" }),
        rel("gs", "st", "hosts sessions", { style: "dashed" }),
        rel("ap", "me", "nudges", { style: "dashed" }),
        rel("me", "tr", "grow"),
        rel("ap", "th", "overlaps with", { style: "dotted", direction: "none" }),
      ],
    },
  },
  {
    id: "community-evidence",
    title: "What backs our community bet",
    note: "Because two cards are sources, they become links on the finding each supports, using only the URLs given; the open question stays a caption so it is not read as a finding.",
    labels: ["research", "community"],
    input: {
      type: "canvasCards",
      title: "Research brief cards",
      text: "Connect these findings and sources so the team sees what backs what.",
      cards: [
        { title: "Loneliness drives sign-ups", body: "Top reason in 40 interviews" },
        { title: "Rituals build belonging", body: "Weekly tea circle regulars" },
        { title: "Small groups retain members", body: "Under 12 feels intimate" },
        { title: "Source: ONS wellbeing data", body: "https://www.ons.gov.uk" },
        { title: "Source: APA on social support", body: "https://www.apa.org" },
        { title: "Does this hold online?", body: "Nobody has checked" },
      ],
    },
    graph: {
      mapType: "conceptMap",
      title: "What backs our community bet",
      legend: [],
      nodes: [
        node("f1", "concept", "Loneliness drives sign-ups", { detail: "Top reason in 40 interviews" }),
        node("f2", "concept", "Rituals build belonging", { detail: "Weekly tea circle regulars" }),
        node("f3", "concept", "Small groups retain members", { detail: "Under 12 feels intimate" }),
        node("l1", "concept", "ONS wellbeing data", { kind: "link", props: props({ url: "https://www.ons.gov.uk" }) }),
        node("l2", "concept", "APA on social support", { kind: "link", props: props({ url: "https://www.apa.org" }) }),
        node("q", "concept", "Open question: does this hold online?", { kind: "caption", detail: "Nobody has checked" }),
      ],
      relations: [
        rel("f1", "f2", "leads people to"),
        rel("f2", "f3", "strongest in"),
        rel("l1", "f1", "supports"),
        rel("l2", "f3", "supports"),
        rel("q", "f3", "questions", { style: "dotted" }),
      ],
    },
  },
];
