// Starter exemplars, part 1: headings over regions, a zone holding a table,
// a portal drill-down, colour with meaning on causes, a decision fork, and
// scenes that end in a task.
import type { AuthoredExemplar } from "../types";
import { node, props, rel } from "./helpers";

export const STARTER_1: AuthoredExemplar[] = [
  {
    id: "retreat-weekend",
    title: "Sound retreat weekend",
    note: "A messy retreat dump sorted by day under headings, with the money as a real table and the open decision as a task with an owner.",
    labels: ["retreat", "planning"],
    input: {
      type: "brainDump",
      title: "Sound retreat, unsorted",
      text: "right so the sound retreat in march. friday people arrive from 6, I want it soft: tea, low light, phones in a basket. saturday: gong bath at 9, then a slow walk to the lake, long lunch, afternoon voice workshop with Ana. sunday: closing circle then people leave by 2. money: venue is 4,200 for the weekend, food about 1,500, teachers 1,800. still need to decide shared or private rooms, Leo said he'd price both.",
      cards: [],
    },
    graph: {
      mapType: "spider",
      title: "Sound retreat weekend",
      legend: [],
      nodes: [
        node("c", "center", "Sound retreat", { detail: "March weekend, 18 guests", props: props({ emoji: "🔔" }) }),
        node("h1", "branch", "Friday arrival", { kind: "heading", parent: "c" }),
        node("h2", "branch", "Saturday", { kind: "heading", parent: "c" }),
        node("h3", "branch", "Sunday close", { kind: "heading", parent: "c" }),
        node("h4", "branch", "Money", { kind: "heading", parent: "c" }),
        node("f1", "leaf", "Soft landing", { parent: "h1", detail: "Tea, low light, phones in a basket", props: props({ emoji: "🍵" }) }),
        node("f2", "leaf", "Guests arrive from 6pm", { kind: "caption", parent: "h1" }),
        node("s1", "leaf", "Gong bath", { parent: "h2", detail: "9am in the main hall", props: props({ emoji: "🎶" }) }),
        node("s2", "leaf", "Walk to the lake", { parent: "h2", detail: "Slow and mostly silent" }),
        node("s3", "leaf", "Long lunch", { parent: "h2", detail: "No rush, one long table" }),
        node("s4", "leaf", "Voice workshop", { parent: "h2", detail: "Afternoon, led by Ana" }),
        node("u1", "leaf", "Closing circle", { parent: "h3", detail: "One word each, then goodbyes" }),
        node("u2", "leaf", "Guests leave by 2pm", { kind: "caption", parent: "h3" }),
        node("m1", "leaf", "Budget", {
          kind: "table", parent: "h4",
          props: props({ cells: [["Item", "Cost (EUR)"], ["Venue", "4,200"], ["Food", "1,500"], ["Teachers", "1,800"], ["Total", "7,500"]], headerRow: true }),
        }),
        node("m2", "leaf", "Price shared vs private rooms", { kind: "task", parent: "h4", props: props({ owner: "Leo", emoji: "✅" }) }),
      ],
      relations: [],
    },
  },
  {
    id: "pass-pricing-tiers",
    title: "Experience pass tiers",
    note: "Numbers go in a table inside a zone for the designer's comparison, competitor research becomes a portal, and the next step is a task.",
    labels: ["pricing"],
    input: {
      type: "comparison",
      title: "Three pass tiers",
      text: "We're choosing between three experience pass tiers: Drop-in at 18 a visit, Regular at 49 a month for four visits, and Unlimited at 89 a month. Compare them on price per visit and booking window, and tell me what to launch with. We also looked at what three other studios charge, and Mia will write the tier page.",
      cards: [],
    },
    graph: {
      mapType: "tree",
      title: "Experience pass tiers",
      legend: [],
      nodes: [
        node("root", "root", "Pass pricing", { detail: "Launch with three tiers", props: props({ emoji: "🎟️" }) }),
        node("z1", "branch", "Tier comparison", { kind: "zone", parent: "root", detail: "Compare the tiers side by side before choosing the anchor price." }),
        node("t1", "leaf", "Tiers at a glance", {
          kind: "table", parent: "z1",
          props: props({ cells: [["Tier", "Price", "Per visit", "Booking window"], ["Drop-in", "18", "18.00", "3 days"], ["Regular", "49 a month", "12.25", "7 days"], ["Unlimited", "89 a month", "under 9 at 10+", "14 days"]], headerRow: true }),
        }),
        node("c1", "leaf", "Anchor on Regular", { parent: "z1", detail: "Most members land in the middle tier; make it the default choice.", props: props({ emoji: "⚓" }) }),
        node("c2", "leaf", "Founding member price", { parent: "z1", detail: "Unlimited at 69 for the first 100 members.", props: props({ emoji: "🌱" }) }),
        node("p1", "branch", "Competitor pricing", { kind: "portal", parent: "root", detail: "Three studios' passes, screenshots and notes", props: props({ icon: "grid" }) }),
        node("b3", "branch", "Launch offer", { parent: "root", detail: "First visit free with a Regular sign-up", props: props({ emoji: "🎁" }) }),
        node("k1", "leaf", "Draft tier page copy", { kind: "task", parent: "b3", props: props({ owner: "Mia" }) }),
      ],
      relations: [],
    },
  },
  {
    id: "membership-churn",
    title: "Why members cancel",
    note: "Causes coloured by whether they are in our control, with a legend; the two causes we own most are strong, the outside ones dotted as indirect.",
    labels: ["churn", "membership"],
    input: {
      type: "brainDump",
      title: "Why members cancel",
      text: "sound bath studio, members cancelling after month 3. from the exit survey: class times clash with commutes, the app booking is clunky, a few say the price went up. outside stuff too: two new studios opened nearby and summer holidays. when people cancel the evening classes get half empty, teachers lose hours, and we lose word of mouth. the price thing and the booking thing are on us, the rest isn't.",
      cards: [],
    },
    graph: {
      mapType: "multiFlow",
      title: "Why members cancel",
      legend: [{ tint: "sunset", meaning: "In our control" }, { tint: "glacier", meaning: "Outside our control" }],
      nodes: [
        node("k1", "cause", "Clashing class times", { tint: "sunset", detail: "Evening slots start before commuters get back", props: props({ emoji: "🕕" }) }),
        node("k2", "cause", "Clunky app booking", { tint: "sunset", detail: "Four taps to book, and it often fails", props: props({ emoji: "📱" }) }),
        node("k3", "cause", "Price rise", { tint: "sunset", detail: "Up 15% in spring" }),
        node("k4", "cause", "New studios nearby", { tint: "glacier", detail: "Two opened within 1 km" }),
        node("k5", "cause", "Summer holidays", { tint: "glacier" }),
        node("ev", "event", "Member cancels after month 3", { emphasis: "strong", detail: "Cancellations peak in month 3", props: props({ emoji: "🚪" }) }),
        node("e1", "effect", "Half-empty evening classes"),
        node("e2", "effect", "Teachers lose hours"),
        node("e3", "effect", "Less word of mouth"),
      ],
      relations: [
        rel("k1", "ev", "", { weight: "strong" }),
        rel("k2", "ev", "", { weight: "strong" }),
        rel("k3", "ev"),
        rel("k4", "ev", "", { style: "dotted" }),
        rel("k5", "ev", "", { style: "dotted" }),
        rel("ev", "e1"),
        rel("ev", "e2"),
        rel("ev", "e3"),
      ],
    },
  },
  {
    id: "rooftop-go-no-go",
    title: "Rooftop night: go or no-go",
    note: "A decision is a waypoint with two labelled branches, each ending in the tasks it triggers; the deadline is a caption, not a card.",
    labels: ["event", "decision"],
    input: {
      type: "brainDump",
      title: "Rooftop night: go or no-go",
      text: "rooftop listening night on the 14th. if the forecast is clear by tuesday we go: book the heaters, confirm the DJ, send the reminder. if rain risk is over 40% we move indoors to the loft, which only fits 60, so we'd need to cap tickets and email people. can't decide later than tuesday because of the heater deposit. Sam does heaters, Ivy does comms.",
      cards: [],
    },
    graph: {
      mapType: "tree",
      title: "Rooftop night: go or no-go",
      legend: [],
      nodes: [
        node("d", "root", "Go or no-go?", { kind: "waypoint", emphasis: "strong", props: props({ shapeType: "diamond" }) }),
        node("g", "branch", "Go: rooftop", { parent: "d", detail: "Forecast clear", props: props({ emoji: "🌙" }) }),
        node("n", "branch", "No-go: move to the loft", { parent: "d", detail: "The loft fits 60", props: props({ emoji: "🏠" }) }),
        node("c", "branch", "Decide by Tuesday (heater deposit)", { kind: "caption", parent: "d" }),
        node("g1", "leaf", "Book the heaters", { kind: "task", parent: "g", props: props({ owner: "Sam" }) }),
        node("g2", "leaf", "Confirm the DJ", { kind: "task", parent: "g", props: props({ owner: "Ivy" }) }),
        node("g3", "leaf", "Send the reminder", { kind: "task", parent: "g", props: props({ owner: "Ivy" }) }),
        node("n1", "leaf", "Cap tickets at 60", { kind: "task", parent: "n", props: props({ owner: "Ivy" }) }),
        node("n2", "leaf", "Email ticket holders", { kind: "task", parent: "n", props: props({ owner: "Ivy" }) }),
      ],
      relations: [rel("d", "g", "if clear"), rel("d", "n", "if rain > 40%")],
    },
  },
  {
    id: "ocean-room-scenes",
    title: "Ocean room visit, scene by scene",
    note: "A visit told as scenes is a sequence of frames, and it ends in the one action the team must take next, as a task.",
    labels: ["museum", "storyboard"],
    input: {
      type: "topic",
      title: "Ocean room visit",
      text: "Tell the story of a family's visit to the museum's new ocean room as scenes, and end with what our exhibits team should do next.",
      cards: [],
    },
    graph: {
      mapType: "flow",
      title: "Ocean room visit, scene by scene",
      legend: [],
      nodes: [
        node("v1", "step", "Queue at the portal", { kind: "frame", detail: "Blue light spills into the corridor", props: props({ storyboard: true, description: "Anticipation" }) }),
        node("v2", "step", "Sinking in", { kind: "frame", detail: "The floor rumbles, whale song slows", props: props({ storyboard: true, description: "Descent" }) }),
        node("v3", "step", "The deep", { kind: "frame", detail: "Kids lie on the haptic floor", props: props({ storyboard: true, description: "Stillness" }) }),
        node("v4", "step", "Surfacing", { kind: "frame", detail: "Mist at the exit, lights warm up", props: props({ storyboard: true, description: "Return" }) }),
        node("v5", "step", "Test mist levels with families", { kind: "task", detail: "Two sessions before opening", props: props({ owner: "Exhibits team", emoji: "✅" }) }),
      ],
      relations: [rel("v1", "v2"), rel("v2", "v3"), rel("v3", "v4"), rel("v4", "v5")],
    },
  },
];
