// Pure maths for the lab: no I/O, no SDK imports (safe in client components).
import { costOf, getLabModel, JUDGE_MODELS } from "./config";
import { elementUsage } from "./describe";
import type { MapType } from "@/lib/maps/types";
import type { ArmId, Cell, JudgeId, RunConfig, Vote } from "./types";
import { cellCosts, JUDGE_IDS, promptVersionOf, variantKey } from "./types";

export const ELO_START = 1000;
export const ELO_K = 32;

export function expectedScore(ra: number, rb: number): number {
  return 1 / (1 + 10 ** ((rb - ra) / 400));
}

export interface EloEntry { rating: number; games: number; wins: number; ties: number }

const byTime = (votes: Vote[]) => [...votes].sort((x, y) => x.createdAt.localeCompare(y.createdAt));

export function computeElo(votes: Vote[], cellsById: Map<string, Cell>, k = ELO_K): Map<string, EloEntry> {
  const table = new Map<string, EloEntry>();
  const entry = (key: string) => {
    let e = table.get(key);
    if (!e) { e = { rating: ELO_START, games: 0, wins: 0, ties: 0 }; table.set(key, e); }
    return e;
  };
  for (const v of byTime(votes)) {
    const left = cellsById.get(v.leftCellId);
    const right = cellsById.get(v.rightCellId);
    if (!left || !right) continue;
    const kl = variantKey(left);
    const kr = variantKey(right);
    if (kl === kr) continue;
    const a = entry(kl);
    const b = entry(kr);
    const sa = v.winner === "left" ? 1 : v.winner === "right" ? 0 : 0.5;
    const ea = expectedScore(a.rating, b.rating);
    a.rating += k * (sa - ea);
    b.rating += k * ((1 - sa) - (1 - ea));
    a.games++;
    b.games++;
    if (sa === 1) a.wins++;
    if (sa === 0) b.wins++;
    if (sa === 0.5) { a.ties++; b.ties++; }
  }
  return table;
}

/** The model behind each LLM judge; judges without one cannot self-score. */
export const JUDGE_MODEL_IDS: Partial<Record<JudgeId, string>> = { llmStrong: JUDGE_MODELS.strong, llmCheap: JUDGE_MODELS.cheap };

/**
 * Share of non-tie votes where the judge preferred the variant the user
 * preferred (judge ties count ½). With `excludeModelId`, votes where either
 * cell was generated by that model are skipped: a judge grading its own
 * model's output may be biased towards it.
 */
export function judgeAgreement(
  votes: Vote[], cellsById: Map<string, Cell>, judgeId: JudgeId, excludeModelId?: string,
): { agreement: number | null; compared: number } {
  let score = 0;
  let compared = 0;
  for (const v of votes) {
    if (v.winner === "tie") continue;
    const left = cellsById.get(v.leftCellId);
    const right = cellsById.get(v.rightCellId);
    if (excludeModelId && (left?.modelId === excludeModelId || right?.modelId === excludeModelId)) continue;
    const jl = left?.judges.find((j) => j.judgeId === judgeId)?.overall;
    const jr = right?.judges.find((j) => j.judgeId === judgeId)?.overall;
    if (jl == null || jr == null) continue;
    compared++;
    if (jl === jr) score += 0.5;
    else if ((jl > jr) === (v.winner === "left")) score += 1;
  }
  return { agreement: compared ? score / compared : null, compared };
}

const pairKey = (x: string, y: string) => [x, y].sort().join("|");

/** How often the user picks the same winner when a pair is shown again. The ceiling for any judge. */
export function selfConsistency(votes: Vote[]): { consistency: number | null; pairs: number } {
  const groups = new Map<string, string[]>();
  for (const v of votes) {
    const winner = v.winner === "tie" ? "tie" : v.winner === "left" ? v.leftCellId : v.rightCellId;
    const key = pairKey(v.leftCellId, v.rightCellId);
    groups.set(key, [...(groups.get(key) || []), winner]);
  }
  const repeated = Array.from(groups.values()).filter((w) => w.length >= 2);
  if (repeated.length === 0) return { consistency: null, pairs: 0 };
  const consistent = repeated.filter((w) => w.every((x) => x === w[0])).length;
  return { consistency: consistent / repeated.length, pairs: repeated.length };
}

/** Token assumptions per arm, used only for the pre-run estimate. Actual cost is measured. */
export const ARM_TOKENS: Record<ArmId, { input: number; output: number }> = {
  baseline: { input: 6000, output: 4000 },
  graph: { input: 4000, output: 3000 },
  graphCritique: { input: 10000, output: 6000 },
  // The guide (~1.4k tokens) plus up to 3 selected exemplars, each with its
  // input and graph JSON (the block itself measures ~1.6k-2k tokens across
  // the corpus, chars/4, since select-v3-relevance; down from ~8.8k when the
  // library always showed the same 3 examples verbatim). ~4000 tokens covers
  // the measured max (~3.3k guide+block, plus the task input) with margin;
  // lab-math.verify's corpus measurement must stay under this.
  graphExemplars: { input: 4000, output: 3500 },
};
/** Per LLM-judge call; the description now carries tints, legend, emphasis and connector styles. */
export const JUDGE_TOKENS = { input: 4000, output: 700 };

export function estimateRunCost(config: RunConfig): number {
  const perArmModel = config.inputIds.length;
  let total = 0;
  for (const modelId of config.modelIds) {
    const model = getLabModel(modelId);
    for (const arm of config.arms) total += perArmModel * costOf(model, ARM_TOKENS[arm].input, ARM_TOKENS[arm].output);
  }
  const cells = config.inputIds.length * config.arms.length * config.modelIds.length;
  if (config.judges.includes("llmStrong")) total += cells * costOf(getLabModel(JUDGE_MODELS.strong), JUDGE_TOKENS.input, JUDGE_TOKENS.output);
  if (config.judges.includes("llmCheap")) total += cells * costOf(getLabModel(JUDGE_MODELS.cheap), JUDGE_TOKENS.input, JUDGE_TOKENS.output);
  return total;
}

export interface PairPick { left: Cell; right: Cell; repeat: boolean }

/**
 * May this cell be shown for voting? Only maps that rendered cleanly: done,
 * with no structure violations (which include connector crossings) and no
 * rubric errors. Cells stored before crossings failed a cell are caught by
 * their rubric judge: on a done cell, a failing rubric means crossings.
 */
export function votable(c: Cell): boolean {
  return c.status === "done" && c.elements.length > 0 &&
    c.structureViolations.length === 0 && c.rubricErrors.length === 0 &&
    !c.judges.some((j) => j.judgeId === "rubric" && !j.pass);
}

/**
 * Next pair to judge: two votable cells for the same input from different
 * variants, never shown before. About 10% of the time (once 10+ votes exist) a
 * judged pair is re-shown with sides swapped, to measure self-consistency.
 * With `promptVersion`, only cells generated with that prompt version are
 * offered, so new votes count on the default leaderboard.
 */
export interface PickOptions {
  /** Only cells generated with this prompt version. */
  promptVersion?: string;
  /**
   * Old-vs-new mode: only cells of these two versions, paired with the same
   * input, arm, model and forced type in the other version.
   */
  versions?: [string, string];
}

export function pickPair(
  cells: Cell[], votes: Vote[], rng: () => number = Math.random, opts: PickOptions = {},
): PairPick | null {
  const inVersions = (c: Cell) => !opts.versions || opts.versions.includes(promptVersionOf(c));
  const eligible = withoutSuperseded(cells).filter((c) => votable(c) && inVersions(c) &&
    (opts.promptVersion === undefined || promptVersionOf(c) === opts.promptVersion));
  const pairable = (x: Cell, y: Cell) => (opts.versions
    ? variantKey(x) === variantKey(y) && promptVersionOf(x) !== promptVersionOf(y)
    : variantKey(x) !== variantKey(y));
  const byInput = new Map<string, Cell[]>();
  for (const c of eligible) byInput.set(c.inputId, [...(byInput.get(c.inputId) || []), c]);

  const seen = new Set(votes.map((v) => pairKey(v.leftCellId, v.rightCellId)));
  const candidates: [Cell, Cell][] = [];
  Array.from(byInput.values()).forEach((group) => {
    for (let i = 0; i < group.length; i++) {
      for (let j = i + 1; j < group.length; j++) {
        if (pairable(group[i], group[j])) candidates.push([group[i], group[j]]);
      }
    }
  });
  if (candidates.length === 0) return null;

  const orient = ([x, y]: [Cell, Cell], repeat: boolean): PairPick =>
    rng() < 0.5 ? { left: x, right: y, repeat } : { left: y, right: x, repeat };

  const judged = candidates.filter(([x, y]) => seen.has(pairKey(x.id, y.id)));
  if (votes.length >= 10 && judged.length > 0 && rng() < 0.1) {
    return orient(judged[Math.floor(rng() * judged.length)], true);
  }
  const fresh = candidates.filter(([x, y]) => !seen.has(pairKey(x.id, y.id)));
  if (fresh.length === 0) return null;
  return orient(fresh[Math.floor(rng() * fresh.length)], false);
}

export interface LeaderboardRow {
  variant: string;
  arm: string;
  modelId: string;
  forcedType: MapType | null;
  rating: number;
  games: number;
  wins: number;
  ties: number;
  cells: number;
  failures: number;
  failureRate: number;
  /** Generation + judges. */
  costUsd: number;
  genCostUsd: number;
  judgeCostUsd: number;
  /** Generation cost per win: what the variant costs to produce, not to grade. */
  costPerWin: number | null;
  /** Mean elementFit from the strong / cheap LLM judge over done cells; null when none scored it. */
  elementFitStrong: number | null;
  elementFitCheap: number | null;
  /** Mean distinct element kinds per rendered map (done cells). */
  kindsPerMap: number | null;
  /** Mean share of plain note cards among rendered elements (done cells). */
  plainCardShare: number | null;
}

const mean = (xs: number[]): number | null => (xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : null);

/** Cells without the originals that a re-scored copy (Cell.rescoredFrom) stands in for. */
export function withoutSuperseded(cells: Cell[]): Cell[] {
  const superseded = new Set<string>();
  cells.forEach((c) => { if (c.rescoredFrom) superseded.add(c.rescoredFrom); });
  return superseded.size ? cells.filter((c) => !superseded.has(c.id)) : cells;
}

/** A judge's elementFit on a cell, or null (not judged, judge failed, or a cell from before elementFit existed). */
function elementFitOf(c: Cell, judgeId: JudgeId): number | null {
  const v = c.judges.find((j) => j.judgeId === judgeId)?.scores?.elementFit;
  return typeof v === "number" ? v : null;
}

export interface Leaderboard {
  rows: LeaderboardRow[];
  byMapType: { mapType: string; variant: string; wins: number; games: number }[];
  judges: {
    judgeId: JudgeId; agreement: number | null; compared: number;
    /** Agreement over votes where neither cell came from the judge's own model. */
    agreementExSelf: number | null; comparedExSelf: number;
  }[];
  selfConsistency: number | null;
  repeatedPairs: number;
  totalVotes: number;
  /** The prompt version counted, or null when every version is counted. */
  promptVersion: string | null;
  /** Cells and votes left out because they were made with another prompt version (or are legacy). */
  excludedCells: number;
  excludedVotes: number;
}

export interface LeaderboardOptions {
  /** Count only cells with this prompt version (legacy cells never match); omit for all versions. */
  promptVersion?: string;
}

export function buildLeaderboard(allCells: Cell[], allVotes: Vote[], opts: LeaderboardOptions = {}): Leaderboard {
  const pv = opts.promptVersion;
  const live = withoutSuperseded(allCells);
  const cells = pv === undefined ? live : live.filter((c) => promptVersionOf(c) === pv);
  const cellsById = new Map(cells.map((c) => [c.id, c]));
  // A vote counts only when both of its cells do.
  const votes = allVotes.filter((v) => cellsById.has(v.leftCellId) && cellsById.has(v.rightCellId));
  const elo = computeElo(votes, cellsById);

  const perVariant = new Map<string, {
    cells: number; failures: number; gen: number; judge: number; arm: string; modelId: string; forcedType: MapType | null;
    fitStrong: number[]; fitCheap: number[]; kinds: number[]; cardShare: number[];
  }>();
  for (const c of cells) {
    if (c.status === "pending" || c.status === "running" || c.status === "skipped") continue;
    const key = variantKey(c);
    const e = perVariant.get(key) || {
      cells: 0, failures: 0, gen: 0, judge: 0, arm: c.arm, modelId: c.modelId, forcedType: c.forcedType ?? null,
      fitStrong: [], fitCheap: [], kinds: [], cardShare: [],
    };
    e.cells++;
    if (c.status === "failed" || c.status === "error") e.failures++;
    const cost = cellCosts(c);
    e.gen += cost.gen;
    e.judge += cost.judge;
    if (c.status === "done") {
      const strong = elementFitOf(c, "llmStrong");
      const cheap = elementFitOf(c, "llmCheap");
      if (strong !== null) e.fitStrong.push(strong);
      if (cheap !== null) e.fitCheap.push(cheap);
      const usage = elementUsage(c.elements);
      e.kinds.push(usage.distinctKinds);
      e.cardShare.push(usage.plainCardShare);
    }
    perVariant.set(key, e);
  }

  const rows: LeaderboardRow[] = Array.from(perVariant.entries()).map(([variant, v]) => {
    const r = elo.get(variant) || { rating: ELO_START, games: 0, wins: 0, ties: 0 };
    return {
      variant, arm: v.arm, modelId: v.modelId, forcedType: v.forcedType,
      rating: Math.round(r.rating), games: r.games, wins: r.wins, ties: r.ties,
      cells: v.cells, failures: v.failures, failureRate: v.cells ? v.failures / v.cells : 0,
      costUsd: v.gen + v.judge, genCostUsd: v.gen, judgeCostUsd: v.judge,
      costPerWin: r.wins ? v.gen / r.wins : null,
      elementFitStrong: mean(v.fitStrong),
      elementFitCheap: mean(v.fitCheap),
      kindsPerMap: mean(v.kinds),
      plainCardShare: mean(v.cardShare),
    };
  }).sort((x, y) => y.rating - x.rating || y.wins - x.wins);

  const typeTable = new Map<string, { mapType: string; variant: string; wins: number; games: number }>();
  for (const v of votes) {
    for (const [id, won] of [[v.leftCellId, v.winner === "left"], [v.rightCellId, v.winner === "right"]] as const) {
      const c = cellsById.get(id);
      if (!c?.mapType) continue;
      const key = `${c.mapType}|${variantKey(c)}`;
      const e = typeTable.get(key) || { mapType: c.mapType, variant: variantKey(c), wins: 0, games: 0 };
      e.games++;
      if (won) e.wins++;
      typeTable.set(key, e);
    }
  }

  const sc = selfConsistency(votes);
  return {
    rows,
    byMapType: Array.from(typeTable.values()).sort((x, y) => x.mapType.localeCompare(y.mapType) || y.wins - x.wins),
    judges: JUDGE_IDS.map((judgeId) => {
      const all = judgeAgreement(votes, cellsById, judgeId);
      const ex = judgeAgreement(votes, cellsById, judgeId, JUDGE_MODEL_IDS[judgeId]);
      return { judgeId, ...all, agreementExSelf: ex.agreement, comparedExSelf: ex.compared };
    }),
    selfConsistency: sc.consistency,
    repeatedPairs: sc.pairs,
    totalVotes: votes.length,
    promptVersion: pv ?? null,
    excludedCells: allCells.length - cells.length,
    excludedVotes: allVotes.length - votes.length,
  };
}

export interface VersionStats {
  version: string;
  cells: number;
  failures: number;
  failureRate: number;
  elementFitStrong: number | null;
  elementFitCheap: number | null;
  kindsPerMap: number | null;
  plainCardShare: number | null;
}

export interface VersionComparison {
  old: VersionStats;
  next: VersionStats;
  votes: { newWins: number; oldWins: number; ties: number };
  verdict: {
    /** Every judge that scored both versions gives the new one a higher mean; null when none did. */
    elementFitRises: boolean | null;
    /** More blind wins for the new version than the old; null before any cross-version vote. */
    votesFavourNew: boolean | null;
    failureRateHolds: boolean;
    success: boolean;
  };
}

/**
 * Spec §6 success criterion on the same inputs and models: only (input, arm,
 * model, forced type) slots that have settled cells in both versions count.
 */
export function compareVersions(cells: Cell[], votes: Vote[], oldVersion: string, newVersion: string): VersionComparison {
  const slot = (c: Cell) => `${c.inputId}|${variantKey(c)}`;
  const live = withoutSuperseded(cells);
  const settled = live.filter((c) => c.status === "done" || c.status === "failed" || c.status === "error");
  const oldAll = settled.filter((c) => promptVersionOf(c) === oldVersion);
  const newAll = settled.filter((c) => promptVersionOf(c) === newVersion);
  const newSlots = new Set(newAll.map(slot));
  const shared = new Set(oldAll.map(slot).filter((s) => newSlots.has(s)));
  const oldCells = oldAll.filter((c) => shared.has(slot(c)));
  const newCells = newAll.filter((c) => shared.has(slot(c)));

  const stats = (version: string, list: Cell[]): VersionStats => {
    const done = list.filter((c) => c.status === "done");
    const failures = list.length - done.length;
    const fits = (judgeId: JudgeId) => done.map((c) => elementFitOf(c, judgeId)).filter((x): x is number => x !== null);
    const usage = done.map((c) => elementUsage(c.elements));
    return {
      version, cells: list.length, failures, failureRate: list.length ? failures / list.length : 0,
      elementFitStrong: mean(fits("llmStrong")), elementFitCheap: mean(fits("llmCheap")),
      kindsPerMap: mean(usage.map((u) => u.distinctKinds)), plainCardShare: mean(usage.map((u) => u.plainCardShare)),
    };
  };
  const old = stats(oldVersion, oldCells);
  const next = stats(newVersion, newCells);

  const byId = new Map(live.map((c) => [c.id, c]));
  const tally = { newWins: 0, oldWins: 0, ties: 0 };
  for (const v of votes) {
    const l = byId.get(v.leftCellId);
    const r = byId.get(v.rightCellId);
    if (!l || !r) continue;
    const lv = promptVersionOf(l);
    const rv = promptVersionOf(r);
    if (!((lv === oldVersion && rv === newVersion) || (lv === newVersion && rv === oldVersion))) continue;
    if (v.winner === "tie") { tally.ties++; continue; }
    const winnerVersion = v.winner === "left" ? lv : rv;
    if (winnerVersion === newVersion) tally.newWins++;
    else tally.oldWins++;
  }

  const fitPairs: [number | null, number | null][] = [
    [old.elementFitStrong, next.elementFitStrong],
    [old.elementFitCheap, next.elementFitCheap],
  ];
  const judged = fitPairs.filter((p): p is [number, number] => p[0] !== null && p[1] !== null);
  const elementFitRises = judged.length ? judged.every(([a, b]) => b > a) : null;
  const decisive = tally.newWins + tally.oldWins;
  const votesFavourNew = decisive ? tally.newWins > tally.oldWins : null;
  const failureRateHolds = next.failureRate <= old.failureRate;
  return {
    old, next, votes: tally,
    verdict: { elementFitRises, votesFavourNew, failureRateHolds, success: elementFitRises === true && votesFavourNew === true && failureRateHolds },
  };
}
