// The example library's pending state and its Publish step. Server-only.
//
// Pending examples live in lab-data/library-pending.json (gitignored), written
// atomically like the other lab stores. Publish writes promoted examples into
// src/lib/maps/exemplars/promoted/ as one batch: every JSON file first, then
// manifest.ts (the single commit point the app loads, so the library and
// PROMPT_VERSION change exactly once), then the cleared pending state. A
// failure before the pending state is saved removes this batch's files and
// restores the previous manifest. Retired files are removed last.
import fs from "node:fs/promises";
import path from "node:path";
import { AUTHORED_EXEMPLARS, fromPromoted } from "@/lib/maps/exemplars";
import { coverageGain, coverageOf, type CoverageGain, type CoverageItem } from "@/lib/maps/exemplars/coverage";
import { faithfulnessProblems } from "@/lib/maps/exemplars/faithful";
import type { Exemplar, ExemplarInput, ExemplarProvenance, ExemplarTags, PromotedExemplarFile } from "@/lib/maps/exemplars/types";
import { closestCorpusClash } from "@/lib/maps/exemplars/similarity";
import { exemplarProblems } from "@/lib/maps/exemplars/validate";
import { upgradeGraph } from "@/lib/maps/legacy";
import { renderMap } from "@/lib/maps/render";
import type { MapGraph } from "@/lib/maps/types";
import type { CanvasEdge, CanvasElement } from "@/types/canvas-elements";
import { LAB_DATA_DIR } from "./config";
import { CORPUS } from "./corpus";
import { computePromptVersion, PROMPT_VERSION } from "./prompts";
import { writeAtomic } from "./store";
import { promptVersionOf, type Cell, type LabInput } from "./types";

const promotedDir = () => path.resolve(process.cwd(), "src", "lib", "maps", "exemplars", "promoted");
const manifestFile = () => path.join(promotedDir(), "manifest.ts");
const pendingFile = () => path.resolve(process.cwd(), LAB_DATA_DIR, "library-pending.json");

/** A request the library refuses for a reason the user can act on (HTTP 409). */
export class LibraryConflictError extends Error {
  override name = "LibraryConflictError";
}
/** An example id or cell that does not exist (HTTP 404). */
export class LibraryNotFoundError extends Error {
  override name = "LibraryNotFoundError";
}

export interface PendingState {
  pending: PromotedExemplarFile[];
  /** Published promoted ids to remove at the next publish. */
  retired: string[];
}

/** Indirection so the offline verify can fail a write part-way. */
export const libraryDeps = {
  writeFile: writeAtomic,
  removeFile: (file: string) => fs.rm(file, { force: true }),
};

export async function readPending(): Promise<PendingState> {
  try {
    const raw = JSON.parse(await fs.readFile(pendingFile(), "utf8")) as Partial<PendingState>;
    return { pending: Array.isArray(raw.pending) ? raw.pending : [], retired: Array.isArray(raw.retired) ? raw.retired : [] };
  } catch {
    return { pending: [], retired: [] };
  }
}

async function savePending(state: PendingState): Promise<void> {
  await fs.mkdir(path.dirname(pendingFile()), { recursive: true });
  await libraryDeps.writeFile(pendingFile(), JSON.stringify(state, null, 2));
}

/**
 * Serializes every mutation of library-pending.json (promote, retire, and
 * publish's final pending clear) through one shared queue, so concurrent
 * calls never read-modify-write from a stale snapshot taken before they got
 * in line — the lost-update race the reviewer flagged (two promotes, or a
 * promote racing a retire or a publish, silently dropping one write). Each
 * step's `run` reads pending state itself, inside the queue, so it always
 * builds on the previous queued mutation's result. Rejects when the step
 * fails, but never blocks later queued steps from running.
 */
let pendingQueue: Promise<unknown> = Promise.resolve();
function withPendingQueue<T>(run: () => Promise<T>): Promise<T> {
  const result = pendingQueue.catch(() => undefined).then(run);
  pendingQueue = result.catch(() => undefined);
  return result;
}

const IMPORT_LINE = /^import e\d+ from "\.\/([a-z0-9-]+)\.json";$/gm;

/** Ids the manifest loads: the published promoted examples. */
export async function publishedIds(): Promise<string[]> {
  let src: string;
  try {
    src = await fs.readFile(manifestFile(), "utf8");
  } catch {
    return [];
  }
  const ids: string[] = [];
  const re = new RegExp(IMPORT_LINE.source, "gm");
  let m: RegExpExecArray | null;
  while ((m = re.exec(src)) !== null) ids.push(m[1]);
  return ids;
}

/** The generated manifest: one static JSON import per published example (bundler-safe in production). */
export function manifestSource(ids: string[]): string {
  const lines = [
    "// GENERATED by the Structure Lab (Library tab, \"Publish library update\"). Do not edit by hand.",
    'import type { PromotedExemplarFile } from "../types";',
    ...ids.map((id, i) => `import e${i} from "./${id}.json";`),
    "",
    `export const PROMOTED: PromotedExemplarFile[] = [${ids.map((_, i) => `e${i} as unknown as PromotedExemplarFile`).join(", ")}];`,
    "",
  ];
  return lines.join("\n");
}

async function readPromotedFile(id: string): Promise<PromotedExemplarFile> {
  return JSON.parse(await fs.readFile(path.join(promotedDir(), `${id}.json`), "utf8")) as PromotedExemplarFile;
}

async function publishedFiles(): Promise<PromotedExemplarFile[]> {
  return Promise.all((await publishedIds()).map(readPromotedFile));
}

export function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 40) || "example";
}

function cleanLabels(labels: string[]): string[] {
  const out: string[] = [];
  for (const raw of labels) {
    const l = raw.trim().toLowerCase().slice(0, 30);
    if (l && !out.includes(l)) out.push(l);
  }
  return out.slice(0, 8);
}

/** The library now (authored + published on disk) and as it will be after publishing `state`. */
function libraries(published: PromotedExemplarFile[], state: PendingState): { current: Exemplar[]; after: Exemplar[] } {
  const current = [...AUTHORED_EXEMPLARS, ...published.map(fromPromoted)];
  const after = [
    ...AUTHORED_EXEMPLARS,
    ...published.filter((p) => !state.retired.includes(p.id)).map(fromPromoted),
    ...state.pending.map(fromPromoted),
  ];
  return { current, after };
}

/**
 * Every check a graph must clear to enter the library: structure (legend
 * rule included), a render with 0 layout errors and 0 connector crossings
 * (validate.ts's exemplarProblems), and faithfulness to the input it was
 * generated from (faithful.ts) — every URL and number the graph states must
 * trace back to that input, so a promoted example never teaches the model to
 * invent facts. Returns the first problem found, or null.
 */
function libraryProblems(input: Pick<ExemplarInput, "title" | "text" | "cards">, graph: MapGraph): string | null {
  const structural = exemplarProblems(graph);
  if (structural.length) return `It fails the library checks (structure, legend or crossings): ${structural[0]}`;
  const unfaithful = faithfulnessProblems(input, graph);
  if (unfaithful.length) return `It states something not in its input (unfaithful): ${unfaithful[0]}`;
  return null;
}

/** Why this cell cannot become an example, or null. */
function promotionProblem(cell: Cell, input: LabInput | undefined, published: PromotedExemplarFile[], state: PendingState): string | null {
  if (cell.status !== "done") return "Only finished maps (status done) can become examples.";
  if (!cell.graph) return "This map has no graph to learn from: only graph arms can be promoted.";
  if (!input) return "The input this map was made from is no longer in the corpus.";
  // Examples must not repeat a test input: the arm would be shown that input's answer.
  const clash = closestCorpusClash(input, CORPUS, input.id);
  if (clash) return `Its input is too close to a corpus input (${clash}); examples must not repeat a test input.`;
  if (cell.structureViolations.length) return `It failed a check: ${cell.structureViolations[0]}`;
  const problem = libraryProblems(input, upgradeGraph(cell.graph));
  if (problem) return problem;
  const taken = [...published, ...state.pending].some((p) => p.provenance.cellId === cell.id);
  if (taken) return "This map is already in the library.";
  return null;
}

export interface PromoteFields { note: string; labels: string[]; title: string }

function toPromotedFile(cell: Cell, input: LabInput, fields: PromoteFields, promotedAt: string): PromotedExemplarFile {
  const graph = upgradeGraph(cell.graph!);
  const suffix = cell.id.replace(/[^a-z0-9]/gi, "").slice(0, 8).toLowerCase();
  const provenance: ExemplarProvenance & { source: "promoted" } = {
    source: "promoted", promptVersion: promptVersionOf(cell), modelId: cell.modelId, promotedAt, cellId: cell.id, inputId: input.id,
  };
  const exampleInput: ExemplarInput = { type: input.type, title: input.title, text: input.text, cards: input.cards };
  return {
    id: `${slug(input.title)}-${suffix}`,
    title: fields.title.trim().slice(0, 120) || graph.title,
    note: fields.note.trim(),
    input: exampleInput,
    graph,
    labels: cleanLabels(fields.labels),
    provenance,
  };
}

export interface PromotionPreview {
  eligible: boolean;
  reason: string | null;
  defaultTitle: string;
  tags: ExemplarTags | null;
  gain: CoverageGain[];
}

/** What promoting this cell would add, or why it cannot be promoted. */
export async function previewPromotion(cell: Cell, input: LabInput | undefined): Promise<PromotionPreview> {
  const state = await readPending();
  const published = await publishedFiles();
  const reason = promotionProblem(cell, input, published, state);
  if (reason) return { eligible: false, reason, defaultTitle: cell.graph?.title ?? "", tags: null, gain: [] };
  const candidate = fromPromoted(toPromotedFile(cell, input!, { note: "preview", labels: [], title: "" }, new Date().toISOString()));
  return {
    eligible: true, reason: null, defaultTitle: candidate.title, tags: candidate.tags,
    gain: coverageGain(libraries(published, state).after, candidate),
  };
}

/** Add a cell's map to the pending library. Throws LibraryConflictError with the reason when it cannot. */
export async function promoteCell(
  cell: Cell, input: LabInput | undefined, fields: PromoteFields, promotedAt = new Date().toISOString(),
): Promise<{ item: PromotedExemplarFile; gain: CoverageGain[] }> {
  const note = fields.note.trim();
  if (!note || note.includes("\n") || note.length > 200) {
    throw new LibraryConflictError("Write a one-line note (up to 200 characters) saying why this map is good.");
  }
  return withPendingQueue(async () => {
    const state = await readPending();
    const published = await publishedFiles();
    const reason = promotionProblem(cell, input, published, state);
    if (reason) throw new LibraryConflictError(reason);
    const item = toPromotedFile(cell, input!, fields, promotedAt);
    const gain = coverageGain(libraries(published, state).after, fromPromoted(item));
    await savePending({ ...state, pending: [...state.pending, item] });
    return { item, gain };
  });
}

/**
 * Retire an example: a pending one is dropped at once, a published one is
 * marked for removal at the next publish (undo clears the mark). Authored
 * examples live in code and are refused.
 */
export async function retireExample(id: string, undo = false): Promise<PendingState> {
  if (AUTHORED_EXEMPLARS.some((e) => e.id === id)) {
    throw new LibraryConflictError("Authored examples live in code: edit src/lib/maps/exemplars/authored/ to change or remove them.");
  }
  return withPendingQueue(async () => {
    const state = await readPending();
    if (state.pending.some((p) => p.id === id)) {
      if (undo) return state;
      const next = { ...state, pending: state.pending.filter((p) => p.id !== id) };
      await savePending(next);
      return next;
    }
    if (!(await publishedIds()).includes(id)) throw new LibraryNotFoundError(`No example ${id} in the library.`);
    const retired = undo ? state.retired.filter((r) => r !== id) : state.retired.includes(id) ? state.retired : [...state.retired, id];
    const next = { ...state, retired };
    await savePending(next);
    return next;
  });
}

export interface PublishResult {
  written: string[];
  removed: string[];
  promptVersion: { before: string; after: string };
}

export async function publishLibrary(): Promise<PublishResult> {
  return withPendingQueue(async () => {
    const state = await readPending();
    if (state.pending.length === 0 && state.retired.length === 0) {
      throw new LibraryConflictError("Nothing to publish: promote or retire an example first.");
    }
    const idsBefore = await publishedIds();
    const published = await Promise.all(idsBefore.map(readPromotedFile));
    for (const p of state.pending) {
      if (idsBefore.includes(p.id)) throw new LibraryConflictError(`${p.id} is already published; retire it first.`);
      const problem = libraryProblems(p.input, upgradeGraph(p.graph));
      if (problem) throw new LibraryConflictError(`${p.id} no longer passes the library checks: ${problem}`);
    }
    const { current, after } = libraries(published, state);
    const before = computePromptVersion(current);
    const afterVersion = computePromptVersion(after);
    const ids = Array.from(new Set([...idsBefore.filter((id) => !state.retired.includes(id)), ...state.pending.map((p) => p.id)])).sort();

    let oldManifest: string | null = null;
    try {
      oldManifest = await fs.readFile(manifestFile(), "utf8");
    } catch {
      oldManifest = null;
    }
    const written: string[] = [];
    let manifestWritten = false;
    try {
      await fs.mkdir(promotedDir(), { recursive: true });
      for (const p of state.pending) {
        const file = path.join(promotedDir(), `${p.id}.json`);
        await libraryDeps.writeFile(file, `${JSON.stringify(p, null, 2)}\n`);
        written.push(file);
      }
      await libraryDeps.writeFile(manifestFile(), manifestSource(ids));
      manifestWritten = true;
      await savePending({ pending: [], retired: [] });
    } catch (e) {
      for (const f of written) await libraryDeps.removeFile(f).catch(() => undefined);
      if (manifestWritten) {
        if (oldManifest !== null) await libraryDeps.writeFile(manifestFile(), oldManifest).catch(() => undefined);
        else await libraryDeps.removeFile(manifestFile()).catch(() => undefined);
      }
      throw e;
    }
    // Committed. The manifest no longer loads retired files; removing them is housekeeping.
    const removed: string[] = [];
    for (const id of state.retired) {
      if (!idsBefore.includes(id)) continue;
      await libraryDeps.removeFile(path.join(promotedDir(), `${id}.json`)).then(() => { removed.push(id); }, () => undefined);
    }
    return { written: state.pending.map((p) => p.id), removed, promptVersion: { before, after: afterVersion } };
  });
}

export type LibraryStatus = "authored" | "published" | "pending" | "retiring";

export interface LibraryItem {
  id: string;
  title: string;
  note: string;
  status: LibraryStatus;
  tags: ExemplarTags;
  input: ExemplarInput;
  provenance: ExemplarProvenance;
  elements: CanvasElement[];
  edges: CanvasEdge[];
  /** Why Retire is unavailable, or null. */
  retireBlocked: string | null;
}

export interface LibraryView {
  items: LibraryItem[];
  coverage: { current: CoverageItem[]; afterPublish: CoverageItem[] };
  pendingCount: number;
  retiringCount: number;
  promptVersion: {
    /** What this server stamps on new cells now. */
    running: string;
    /** The version of the library on disk (differs from running until the dev server reloads the manifest). */
    onDisk: string;
    afterPublish: string;
  };
}

function toItem(e: Exemplar, status: LibraryStatus): LibraryItem {
  let elements: CanvasElement[] = [];
  let edges: CanvasEdge[] = [];
  try {
    const r = renderMap(e.graph);
    elements = r.elements;
    edges = r.edges;
  } catch {
    // A preview that cannot render shows the empty state; the checks report why.
  }
  return {
    id: e.id, title: e.title, note: e.note, status, tags: e.tags, input: e.input, provenance: e.provenance, elements, edges,
    retireBlocked: status === "authored" ? "Authored examples live in code (src/lib/maps/exemplars/authored/)." : null,
  };
}

export async function listLibrary(): Promise<LibraryView> {
  const state = await readPending();
  const published = await publishedFiles();
  const { current, after } = libraries(published, state);
  return {
    items: [
      ...AUTHORED_EXEMPLARS.map((e) => toItem(e, "authored")),
      ...published.map((p) => toItem(fromPromoted(p), state.retired.includes(p.id) ? "retiring" : "published")),
      ...state.pending.map((p) => toItem(fromPromoted(p), "pending")),
    ],
    coverage: { current: coverageOf(current), afterPublish: coverageOf(after) },
    pendingCount: state.pending.length,
    retiringCount: state.retired.length,
    promptVersion: { running: PROMPT_VERSION, onDisk: computePromptVersion(current), afterPublish: computePromptVersion(after) },
  };
}
