// GENERATED by the Structure Lab (Library tab, "Publish library update"). Do not edit by hand.
import type { PromotedExemplarFile } from "../types";

export const PROMOTED: PromotedExemplarFile[] = [];
